version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: embedcache
    main: ./cmd/embedcache
    binary: embedcache
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: embedcache
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^docs:"

release:
  github:
    owner: Ajay6601
    name: embedcache
